# This is a basic workflow to help you get started with Actions

name: PR-Synchronize

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types:
      - synchronize

  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4


      - name: Echo Built-in variables
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "Github context: ${{ toJSON(github) }}"
          echo "Github secrets: ${{ toJSON(secrets) }}"
          echo "Github env: ${{ toJSON(env) }}"
          echo "Github job: ${{ toJSON(job) }}"
        
          echo "-----------------------------------"
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, this was triggered by PR synchronize event!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
